import * as fs from 'fs/promises';
import * as path from 'path';
import { Config, expandHome, readConfig } from '../lib/config';
import { backupPath } from '../lib/backup';
import { checkSymlinkState, createSymlink, removeSymlink } from '../lib/symlink';

const MANAGED_MARKER = '<!-- sync-spells:global-guidance -->';

type GuidanceMode = 'symlink' | 'wrapper';

export type GuidanceAction =
  | 'linked'
  | 'written'
  | 'updated'
  | 'backed-up'
  | 'skipped'
  | 'error';

export type GuidanceStatusState =
  | 'linked'
  | 'missing'
  | 'broken'
  | 'real-file'
  | 'wrong-target'
  | 'managed-wrapper';

export interface GuidanceTarget {
  tool: string;
  targetPath: string;
  mode: GuidanceMode;
}

export interface GuidanceSyncResult {
  tool: string;
  source: string;
  target: string;
  action: GuidanceAction;
  error?: string;
}

export interface GuidanceStatusEntry {
  tool: string;
  source: string;
  target: string;
  state: GuidanceStatusState;
}

const workspaceRootFor = (config: Config): string => {
  const sourceDir = expandHome(config.source);
  return path.basename(sourceDir) === 'skill-category' ? path.dirname(sourceDir) : sourceDir;
};

export const getCanonicalGuidancePath = (config: Config): string =>
  path.join(workspaceRootFor(config), 'AGENTS.md');

export const getGuidanceTargets = (config: Config): GuidanceTarget[] => {
  const targets: GuidanceTarget[] = [];

  const codex = config.tools.codex;
  if (codex?.enabled) {
    targets.push({
      tool: 'codex',
      targetPath: path.join(expandHome(codex.configPath), 'AGENTS.md'),
      mode: 'symlink',
    });
  }

  const claude = config.tools['claude-code'];
  if (claude?.enabled) {
    targets.push({
      tool: 'claude-code',
      targetPath: path.join(expandHome(claude.configPath), 'CLAUDE.md'),
      mode: 'symlink',
    });
  }

  const kiro = config.tools.kiro;
  if (kiro?.enabled) {
    targets.push({
      tool: 'kiro',
      targetPath: path.join(expandHome(kiro.configPath), 'steering', 'global.md'),
      mode: 'wrapper',
    });
  }

  return targets;
};

const kiroWrapperContent = (canonicalPath: string): string => `# Kiro CLI Global Steering

${MANAGED_MARKER}

This file is generated by sync-spells. Keep shared global guidance in:

${canonicalPath}

Kiro CLI does not use AGENTS.md as its native global steering file, so this wrapper points Kiro at the shared source while keeping Kiro-specific runtime config under ~/.kiro.

## Shared Guidance

Read and follow the canonical global guidance in ${canonicalPath}.

## Kiro Runtime Paths

- Global skills: ~/.kiro/skills
- Global agents: ~/.kiro/agents
- Global MCP/settings: ~/.kiro/settings
- Project MCP/settings: .kiro/settings
`;

const syncSymlinkTarget = async (
  tool: string,
  source: string,
  target: string,
): Promise<GuidanceSyncResult> => {
  const state = await checkSymlinkState(target, source);

  switch (state) {
    case 'linked':
      return { tool, source, target, action: 'skipped' };

    case 'missing':
      await fs.mkdir(path.dirname(target), { recursive: true });
      await createSymlink(source, target);
      return { tool, source, target, action: 'linked' };

    case 'real-dir':
      await backupPath(target);
      await fs.rm(target, { recursive: true, force: true });
      await createSymlink(source, target);
      return { tool, source, target, action: 'backed-up' };

    case 'broken':
    case 'wrong-target':
      await removeSymlink(target);
      await createSymlink(source, target);
      return { tool, source, target, action: 'updated' };
  }
};

const syncWrapperTarget = async (
  tool: string,
  source: string,
  target: string,
): Promise<GuidanceSyncResult> => {
  const desired = kiroWrapperContent(source);

  try {
    const current = await fs.readFile(target, 'utf8');
    if (current === desired) {
      return { tool, source, target, action: 'skipped' };
    }

    if (!current.includes(MANAGED_MARKER)) {
      await backupPath(target);
      await fs.writeFile(target, desired, 'utf8');
      return { tool, source, target, action: 'backed-up' };
    }

    await fs.writeFile(target, desired, 'utf8');
    return { tool, source, target, action: 'updated' };
  } catch {
    await fs.mkdir(path.dirname(target), { recursive: true });
    await fs.writeFile(target, desired, 'utf8');
    return { tool, source, target, action: 'written' };
  }
};

export const runGuidanceSync = async (config?: Config): Promise<GuidanceSyncResult[]> => {
  const resolvedConfig = config ?? await readConfig();
  if (!resolvedConfig.source) {
    throw new Error('No source configured. Run `spells setup` first.');
  }

  const source = getCanonicalGuidancePath(resolvedConfig);
  const targets = getGuidanceTargets(resolvedConfig);

  try {
    await fs.access(source);
  } catch {
    return targets.map((target) => ({
      tool: target.tool,
      source,
      target: target.targetPath,
      action: 'error',
      error: 'canonical AGENTS.md not found',
    }));
  }

  const results: GuidanceSyncResult[] = [];
  for (const target of targets) {
    try {
      const result =
        target.mode === 'wrapper'
          ? await syncWrapperTarget(target.tool, source, target.targetPath)
          : await syncSymlinkTarget(target.tool, source, target.targetPath);
      results.push(result);
    } catch (e) {
      results.push({
        tool: target.tool,
        source,
        target: target.targetPath,
        action: 'error',
        error: e instanceof Error ? e.message : String(e),
      });
    }
  }

  return results;
};

const wrapperStatus = async (target: string): Promise<GuidanceStatusState> => {
  try {
    const current = await fs.readFile(target, 'utf8');
    return current.includes(MANAGED_MARKER) ? 'managed-wrapper' : 'real-file';
  } catch {
    return 'missing';
  }
};

export const runGuidanceStatus = async (config?: Config): Promise<GuidanceStatusEntry[]> => {
  const resolvedConfig = config ?? await readConfig();
  if (!resolvedConfig.source) {
    throw new Error('No source configured. Run `spells setup` first.');
  }

  const source = getCanonicalGuidancePath(resolvedConfig);
  const entries: GuidanceStatusEntry[] = [];

  for (const target of getGuidanceTargets(resolvedConfig)) {
    const state =
      target.mode === 'wrapper'
        ? await wrapperStatus(target.targetPath)
        : await checkSymlinkState(target.targetPath, source);

    entries.push({
      tool: target.tool,
      source,
      target: target.targetPath,
      state: state === 'real-dir' ? 'real-file' : state,
    });
  }

  return entries;
};
